version: "3"
services:
  app:
    build: ./backend
    container_name: backend_con
    env_file:
      - db.env
    depends_on:
      - db
    ports:
    - 8000:8000
  db:
    image: postgres
    container_name: postgres_con
    env_file:
      - db.env
    ports:
    - 5432:5432
    volumes:
      - ./lnwza.sql:/docker-entrypoint-initdb.d/lnwza.sql
      - ./dbfinal/:/var/lib/postgresql/data/
  web:
    build: ./frontend
    container_name: frontend_con
    ports:
      - "3000:3000"

volumes:
  dbfinal:


#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin_container
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: 12345
#     depends_on:
#       - db
#     ports:
#       - "5050:80"
#     networks:
#       - fullstack
#     restart: unless-stopped
#   web:
#     build: ./frontend
#     image: silversky9/team-10-frontend:1.0
#     container_name: nginx_container
#     ports:
#       - "80:80"
#     depends_on:
#       - app
#     # volumes:
#     # - ./out:/usr/share/nginx/html
#     networks:
#       - fullstack

# networks:
#   fullstack:
#     driver: bridge
